<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-11T11:57:35Z" name="Suite" finished-at="2022-01-11T11:57:47Z" duration-ms="12629">
    <groups>
    </groups>
    <test started-at="2022-01-11T11:57:35Z" name="Test1" finished-at="2022-01-11T11:57:46Z" duration-ms="11396">
      <class name="screenshotTestNGListener.TakeScreenshotTestNGListener2">
        <test-method is-config="true" signature="startApp()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener2@1a72a540]" started-at="2022-01-11T17:27:35Z" name="startApp" finished-at="2022-01-11T17:27:42Z" duration-ms="7041" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle1000()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener2@1a72a540]" started-at="2022-01-11T17:27:42Z" name="validateTitle1000" finished-at="2022-01-11T17:27:45Z" duration-ms="3005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle1000 -->
        <test-method signature="validateTitle999()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener2@1a72a540]" started-at="2022-01-11T17:27:45Z" name="validateTitle999" finished-at="2022-01-11T17:27:46Z" duration-ms="816" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at screenshotTestNGListener.TakeScreenshotTestNGListener2.validateTitle999(TakeScreenshotTestNGListener2.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle999 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener2@1a72a540]" started-at="2022-01-11T17:27:46Z" name="tearDown" finished-at="2022-01-11T17:27:46Z" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- screenshotTestNGListener.TakeScreenshotTestNGListener2 -->
    </test> <!-- Test1 -->
    <test started-at="2022-01-11T11:57:35Z" name="Test" finished-at="2022-01-11T11:57:47Z" duration-ms="12629">
      <class name="screenshotTestNGListener.TakeScreenshotTestNGListener">
        <test-method is-config="true" signature="startApp()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener@1722011b]" started-at="2022-01-11T17:27:35Z" name="startApp" finished-at="2022-01-11T17:27:41Z" duration-ms="6421" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener@1722011b]" started-at="2022-01-11T17:27:41Z" name="validateTitle" finished-at="2022-01-11T17:27:47Z" duration-ms="5406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateTitle123()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener@1722011b]" started-at="2022-01-11T17:27:47Z" name="validateTitle123" finished-at="2022-01-11T17:27:47Z" duration-ms="289" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at screenshotTestNGListener.TakeScreenshotTestNGListener.validateTitle123(TakeScreenshotTestNGListener.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle123 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:screenshotTestNGListener.TakeScreenshotTestNGListener@1722011b]" started-at="2022-01-11T17:27:47Z" name="tearDown" finished-at="2022-01-11T17:27:47Z" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- screenshotTestNGListener.TakeScreenshotTestNGListener -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
